server:
  port: 5000

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: bankAccount
      username: root
      password: root
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer